### ISSUE TITLE
How to solve error message

### ISSUE THREAD

**Issue by ricardmc99** [dewv/nlcAttendance#11]
@smattingly @codybroyles I have this error when I try to run Mocha.
I did:
`npm install`
`npm install -g npm-install-peers`
`npm run mocha`
And then I have this long error message:
```
> nlcAttendance@0.0.0 mocha /home/ubuntu/workspace/nlcAttendance
> _mocha ./furl/furlsails/test/lifecycle.js ./furl/test

/home/ubuntu/workspace/nlcAttendance/furl/furlsails/test/lifecycle.js:1
(function (exports, require, module, __filename, __dirname) { let sails = require('sails');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/shared/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mnt/shared/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/mnt/shared/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/mnt/shared/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nlcAttendance@0.0.0 mocha: `_mocha ./furl/furlsails/test/lifecycle.js ./furl/test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nlcAttendance@0.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-02-05T19_02_08_008Z-debug.log
```

**Comment by smattingly** [comment]
Most likely it is due to c9's default node installation being a very old version. If that's it, the commands you need to run are *approximately* these. I should have kept a record.
```
nvm install v11
nvm use v11
nvm alias default v11
```

Let me know how that works out.

**Comment by ricardmc99** [comment]
@smattingly I have the v11.7.0. I tired `nvm use v11` and `nvm alias default v11` just in case I wasn't using it but I still get the error.

**Comment by smattingly** [comment]
@ricardmc99 Try this: `npm install -g mocha@latest`

**Comment by tydingsl** [comment]
Did this fix your problem?

**Comment by tydingsl** [comment]
@ricardmc99  ^

**Comment by ricardmc99** [comment]
@tydingsl yes. the last command solves the problem
