### ISSUE TITLE
Check-out editform for Visit

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#23]
The Visit component must support editing existing records (known as a "check out"). So, the visit folder will contain editForm.html, named in anticipation that the RestController can be used.

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 @tydingsl Can I do the logoutTimer.js and HTML so I can have this two editForms done?

**Comment by ricardmc99** [comment]
🍅 working on test

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 trying to solve this error:
```
> nlcAttendance@0.0.0 mocha /home/ubuntu/workspace/nlcAttendance
> mysql-ctl start 2> /dev/null; nyc ./node_modules/.bin/_mocha --recursive ./test/lifecycle.js ./test

 * Starting MySQL database server mysqld
   ...done.
{"path":"views/pages/visit/createForm.html"}
{"path":"views/pages/visit/editForm.html"}


(node:3627) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/parse.js:69:26)
    at module.exports (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/static.js:27:14)
    at new ViewTests (/home/ubuntu/workspace/nlcAttendance/test/views/Views.js:14:25)
    at /home/ubuntu/workspace/nlcAttendance/test/views/visit/createForm.js:35:28
    at tryHandleCache (/home/ubuntu/workspace/nlcAttendance/node_modules/ejs/lib/ejs.js:226:12)
    at Object.exports.renderFile (/home/ubuntu/workspace/nlcAttendance/node_modules/ejs/lib/ejs.js:437:10)
    at Suite.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/createForm.js:30:13)
    at Object.create (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Suite.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/createForm.js:8:5)
    at Object.create (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/createForm.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at runMain (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:68:10)
    at Function.<anonymous> (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:171:5)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at /home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:178:8
    at Object.<anonymous> (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
(node:3627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3627) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/parse.js:69:26)
    at module.exports (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/home/ubuntu/workspace/nlcAttendance/node_modules/cheerio/lib/static.js:27:14)
    at new ViewTests (/home/ubuntu/workspace/nlcAttendance/test/views/Views.js:14:25)
    at /home/ubuntu/workspace/nlcAttendance/test/views/visit/editForm.js:35:28
    at tryHandleCache (/home/ubuntu/workspace/nlcAttendance/node_modules/ejs/lib/ejs.js:226:12)
    at Object.exports.renderFile (/home/ubuntu/workspace/nlcAttendance/node_modules/ejs/lib/ejs.js:437:10)
    at Suite.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/editForm.js:30:13)
    at Object.create (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Suite.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/editForm.js:8:5)
    at Object.create (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/test/views/visit/editForm.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at runMain (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:68:10)
    at Function.<anonymous> (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:171:5)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at /home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:178:8
    at Object.<anonymous> (/home/ubuntu/.node-spawn-wrap-3620-65d66283ee9c/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
(node:3627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3627) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:3627) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
  Staff model
    Standard tests of model, helpers integration
      `getDefaults` helper
        ✓ should return a record with expected sailsjs model attributes
      `getAssociationDomains` helper
        ✓ should return a dictionary containing domain values for each appropriate model attribute
      `encodeAssociations` helper
        ✓ should replace the specified record's domain values with keys for each associated sailsjs model
      `populateOne` helper
        ✓ should return a data record for the specified ID, with all associations populated
      `getCurrentTime helper
        ✓ should return the current synchronized time

  Student model
    Standard tests of model, helpers integration
      `getDefaults` helper
        ✓ should return a record with expected sailsjs model attributes
      `getAssociationDomains` helper
        ✓ should return a dictionary containing domain values for each appropriate model attribute
      `encodeAssociations` helper
        ✓ should replace the specified record's domain values with keys for each associated sailsjs model
      `populateOne` helper
        ✓ should return a data record for the specified ID, with all associations populated
      `getCurrentTime helper
        ✓ should return the current synchronized time
    Visit model
      Test for Visit Model
        `Test the association of the student model for name attribute.
          ✓ Returns correct id number
        `Test the postPopulate function,
27
          ✓ Attribute visitLength was calculated correctly
28
          ✓ Attribute isLengthEstimated is set to true when visitLength is longer that 5 hours.
    A data record returned by `create()`
      ✓ should have a field for each model attribute
      ✓ should have correct default field values

  Standard tests of views, helper integration
    `generateHtmlSelect` helper
      ✓ should provide a <select> tag with <option>s
    `responseViewSafely` helper
      ✓ should call `response.notFound()` when a non-existent file is requested

  Student views
    The edit form
      ✓ should include a text input to edit the first name
      ✓ should include a text input to edit the last name
      ✓ should include select options to edit the fall sport
      ✓ should include select options to edit the spring sport
      ✓ should include a submit button to send the form


  22 passing (3s)
```

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅  trying to solve this error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nlcAttendance@0.0.0 mocha: `mysql-ctl start 2> /dev/null; nyc ./node_modules/.bin/_mocha --recursive ./test/lifecycle.js ./test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nlcAttendance@0.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-13T13_57_05_911Z-debug.log
```

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 not sure how to test text areas

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 @smattingly I have 3 test that I don't know how to make them to pass. Can we look at it next meeting?

**Comment by smattingly** [comment]
> 
> 
> 🍅 @smattingly I have 3 test that I don't know how to make them to pass. Can we look at it next meeting?

Sure.

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 formSelectOption testing

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 coverage still not 95%, doing more testing to put it above 95

**Comment by smattingly** [comment]
Let's look at this before you invest too much effort. The test coverage measures lines of JavaScript covered-- testing of the HTML/EJS stuff will have no impact.

**Comment by smattingly** [comment]
OBE
