### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ricardmc99** [dewv/nlcAttendance#51]
@smattingly @codybroyles @tydingsl 
When I run `npm run test` I have a sintax error on this Test of the student model. I have been looking at it but I couldn't find a solution.
https://github.com/dewv/nlcAttendance/blob/8443181b68be2ab0a5654d1d85ee55cca42fc9b2/test/models/Student.js#L92

**Comment by smattingly** [comment]
What is the error message?
BTW, please save the "bug" label for problems that are discovered on the master branch, or at least that have left one person's branch and been shared with others. Arguably it would be better to post questions like these just as comments with an @mention seeking help.

**Comment by ricardmc99** [comment]
```
> nlcAttendance@0.0.0 mocha /home/ubuntu/workspace/nlcAttendance
> mysql-ctl start 2> /dev/null; nyc ./node_modules/.bin/_mocha --recursive ./test/lifecycle.js ./test

 * Starting MySQL database server mysqld
   ...done.
/home/ubuntu/workspace/nlcAttendance/test/models/Student.js:92
    };
    ^

SyntaxError: missing ) after argument list
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module.replacementCompile (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at runMain (/home/ubuntu/.node-spawn-wrap-2505-3a06660472d1/node:68:10)
    at Function.<anonymous> (/home/ubuntu/.node-spawn-wrap-2505-3a06660472d1/node:171:5)
    at Object.<anonymous> (/home/ubuntu/workspace/nlcAttendance/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at /home/ubuntu/.node-spawn-wrap-2505-3a06660472d1/node:178:8
    at Object.<anonymous> (/home/ubuntu/.node-spawn-wrap-2505-3a06660472d1/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nlcAttendance@0.0.0 mocha: `mysql-ctl start 2> /dev/null; nyc ./node_modules/.bin/_mocha --recursive ./test/lifecycle.js ./test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nlcAttendance@0.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-02-25T02_50_26_079Z-debug.log
```
