### ISSUE TITLE
Fix Staff List

### ISSUE THREAD

**Issue by codybroyles** [dewv/nlcAttendance#63]
I have run into a issue that I can not seem to fix. @smattingly If you could take a look at this on the fallStaff branch. The following error occurs when loading the list and refers to the populate call in the listRequest() function of the REST controller. 

```
OperationalError [AdapterError]: Unexpected error from database adapter: Could not find a primary key for a record. Perhaps it wasn't selected in the query. The primary key was set to: id and the record returned was: RowDataPacket {
  studentId__createdAt: 1567805571514,
  studentId__updatedAt: 1567805571514,
  studentId__id: 2,
  studentId__username: 'USERNAME2@DEWV.NET',
  studentId__firstName: 'FIRSTNAME2',
  studentId__lastName: 'LASTNAME2',
  studentId__academicRank: 'Sophomore',
  studentId__residentialStatus: 'Commuter',
  studentId__forceUpdate: 1,
  studentId__majorOne: 2,
  studentId__majorTwo: 3,
  studentId__fallSport: 2,
  studentId__springSport: 2
}
    at Object.listRequested [as rest/listrequested] (/home/broylesc/csci/nlcAttendance/api/controllers/RestController.js:18:35)
    at /home/broylesc/csci/nlcAttendance/node_modules/sails/lib/router/bind.js:236:53
    at routeTargetFnWrapper (/home/broylesc/csci/nlcAttendance/node_modules/sails/lib/router/bind.js:392:9)
    at /home/broylesc/csci/nlcAttendance/node_modules/sails/lib/router/bind.js:455:14
    at Layer.handle [as handle_request] (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/layer.js:95:5)
    at /home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/index.js:281:22
    at param (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/index.js:354:14)
    at param (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/index.js:410:3)
    at next (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/index.js:275:10)
    at next (/home/broylesc/csci/nlcAttendance/node_modules/express/lib/router/route.js:127:14)
    at module.exports (/home/broylesc/csci/nlcAttendance/api/policies/isAuthorized.js:74:75)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
```

**Comment by codybroyles** [comment]
@smattingly I have wrote a new helper called populateAssociations. It takes a model and array of records as arguments, and checks if the model provided has defined a afterPopulateAssociations() function (if yes then it passes off the array to the model function for the needed manipulation), then returns the array of records. This seems to be working well now.

**Comment by smattingly** [comment]
This was due to `schema: false` in the Visit model set up. Removed that (default is true) because no current need for it could be identified.
